In [9]:
from sympy import *
import numpy as np

init_printing(use_unicode=False, wrap_line=False, no_global=True)
x,y = symbols ('x,y')
a1, a2 = symbols('a1, a2')

# Matrices and vectors

In [10]:
# linsolve allows you to pass a matrix and a vector as an argument
# X - matrix with features
# X_augmented - augmented matrix with answers

X = Matrix([[4.1, 3.9], [4.7, 4.2]])
X_augmented = Matrix([[4.1, 3.9, 4], [4.7, 4.2, 4.3]])

# When passing an argument like this to linsolve, the function itself first of all
# does matrix-vector scalar multiplication to get a system of equations.
linsolve(X_augmented, [a1, a2])

In [11]:
# Operations with matrices and vectors
X = Matrix([[4.1, 3.9], [4.7, 4.2]])
a = Matrix([a1, a2])
b = Matrix([4, 4.3])

X * a - b

[ 4.1*a1 + 3.9*a2 - 4 ]
[                     ]
[4.7*a1 + 4.2*a2 - 4.3]

In [12]:
x, y, z = symbols('x, y, z')

A = Matrix([[-1,7,-34], [8,8,-48]])
B = Matrix([[4,-7,-4], [3,-4,-3]])
C = Matrix([[5,7,-5,-47], [0,-2,2,10], [-4,-8,-7, 63]])

print (linsolve(A, [x, y]))
print (linsolve(B, [x, y]))
print (linsolve(C, [x, y, z]))

{(-1, -5)}
{(-1, 0)}
{(-2, -6, -1)}


In [13]:
# Inverse matrix and operations
M = Matrix([[1,3,-5],[0,1,2],[0,0,1]])
print ('\n given matrix')
display (M)

print ('\n its cofactor matrix')
display (M.cofactor_matrix())

print ('\n transposed cofactor matrix')
display (M.cofactor_matrix().T)

print ('\n determinant of the matrix')
display (M.det())

print ('\n its inverse matrix')
M_inverse = M.cofactor_matrix().T / M.det()
display (M_inverse)

print ('\n unit matrix (inverse matrix check)')
display (M*M_inverse)


 given matrix


[1  3  -5]
[        ]
[0  1  2 ]
[        ]
[0  0  1 ]


 its cofactor matrix


[1   0   0]
[         ]
[-3  1   0]
[         ]
[11  -2  1]


 transposed cofactor matrix


[1  -3  11]
[         ]
[0  1   -2]
[         ]
[0  0   1 ]


 determinant of the matrix



 its inverse matrix


[1  -3  11]
[         ]
[0  1   -2]
[         ]
[0  0   1 ]


 unit matrix (inverse matrix check)


[1  0  0]
[       ]
[0  1  0]
[       ]
[0  0  1]

# Overdetermined linear systems of equations

In [14]:
# An overdetermined system of linear equations is a system that has more equations than variables.
# In this case, the problem is also solved through approximation using MSE

a1, a2 = symbols('a1, a2')

MSE = 1 / 4 * ((4.1 * a1 + 3.9 * a2 - 4.0)**2 + \
               (4.7 * a1 + 4.2 * a2 - 4.3)**2 + \
               (3.1 * a1 + 2.9 * a2 - 3.0)**2 + \
               (4.9 * a1 + 5.0 * a2 - 4.9)**2)
print (MSE.subs({a1: 0, a2: 0}))

MSEa1 = diff(MSE, a1)
MSEa2 = diff(MSE, a2)

step = 0.01
point = np.array([0, 0])
grad = np.array([MSEa1.subs({a1: point[0], a2: point[1]}), 
                 MSEa2.subs({a1: point[0], a2: point[1]})])

next_point = point - step * grad

print (MSE.subs({a1: next_point[0], a2: next_point[1]}))

16.8750000000000
1.58934775845000


In [19]:
# Another gradient descent
x,y,z = symbols ('x, y, z')

MSE = 1 / 6 * ((5*x + 7*y - 5*z + 47)**2 + \
               (-2*x + 2*z - 10)**2 + \
               (-4*x - 8*y - 7*z - 63)**2 + \
               (x + y + 2*z + 1)**2 + \
               (2*x - y + 2*z + 4)**2 + \
               (4*x + y + 4*z + 2)**2)

print (f'point[0] {MSE.subs({x: 0, y: 0, z: 0})}')

MSEx = diff(MSE, x)
MSEy = diff(MSE, y)
MSEz = diff(MSE, z)

step = 0.01

# point = np.array([0, 0, 0])
point = next_point
grad = np.array([MSEx.subs({x: point[0], y: point[1], z: point[2]}), 
                 MSEy.subs({x: point[0], y: point[1], z: point[2]}),
                 MSEz.subs({x: point[0], y: point[1], z: point[2]})])
                 
next_point = point - step * grad

MSE.subs({x: next_point[0], y: next_point[1], z:next_point[2]})

point[0] 1049.83333333333
