# Линейные модели и нейронные сети. Практическая работа

В этой практической работе пять обязательных задач.

Они помогут понять, что вы действительно усвоили материал модуля. 

Удачи!

## Цели практической работы
Потренироваться в обучении модели:
- линейной регрессии;
- логистической регрессии; 
- многослойного персептрона.

## Что входит в практическую работу

1. Загрузите датасет и ознакомьтесь с ним.
2. Обучите линейную регрессию, включая признаки с нулевым весом и без них. Замерьте качество.
3. Обучите случайный лес. Замерьте качество.
4. Обучите многослойный перцептрон. Замерьте качество.
5. Реализуйте стратегию голосования. Замерьте качество.

## Что оценивается

* Выполнены все задания. В каждом:
 * в коде нет ручных перечислений, все действия автоматизированы;
 * результаты вычислений и применённых операций корректны;
 * ответы на вопросы, где требуется, корректны и обоснованы; 
 * код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов. Стилизация кода соответствует рекомендациям [PEP 8](https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html).
 
* Репозиторий проекта оформлен корректно:
 * содержит осмысленные коммиты, содержащие конкретные реализованные фичи;
 * ветки названы согласно назначению;
 * файлы, не связанные с проектом, не хранятся в репозитории.

## Как отправить работу на проверку

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

## Задача

Постройте модель классификации, определяющую категорию цены / цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Используйте датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.

### Описание датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);
- `price`— стоимость;
- `price_category`— категория цены.

## Обязательные задачи

In [246]:
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier

In [158]:
df = pd.read_csv('data/vehicles_dataset_prepared.csv')
df.head(1)

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  

[1 rows x 1463 columns]

**Задача 1. Линейная регрессия**

Вспомните задачу по предсказанию стоимости подержанного автомобиля. Попробуйте обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого сделайте шаги:

- подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`);
- разделите выборку на треин и тест в отношении 70/30;
- обучите модель линейной регрессии с дефолтными параметрами;
- посчитайте значение метрики mae на тестовой выборке для линейной регрессии;
- выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_` (есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом);
- удалите фичи, коэффициенты которых равны нулю; переобучите модель; убедитесь, что значение метрики не изменилось.



In [159]:
df1 = df.drop(['price_category', 'odometer/price_std'], axis = 1)
print (df.shape)
print (df1.shape)

(9619, 1463)
(9619, 1461)


In [160]:
x = df1.drop(['price'], axis=1)
y = df1['price']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [161]:
lr = LinearRegression()

In [162]:
lr.fit(x_train, y_train)
pred = lr.predict(x_test)
mean_absolute_error(y_test, pred)

4600.341119684605

In [163]:
coefficients = zip (x_test.columns.tolist(), lr.coef_) 
for col, i in coefficients:
    if i == 0:
        print (f'Коэф при колонке {col}={i}')

Коэф при колонке manufacturer_ferrari=0.0


In [164]:
df2= df1.drop(['manufacturer_ferrari'], axis = 1)
x = df2.drop(['price'], axis=1)
y = df2['price']
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)
lr.fit(x_train, y_train)
pred = lr.predict(x_test)
mean_absolute_error(y_test, pred)

4600.341120992148

**Задача 2. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели:

- рассчитайте и выведите метрику качества (accuracy) на тренировочной выборке;
- сделайте предикт на тестовых данных и положите его в переменную `logreg_pred`;
- рассчитайте и выведите accuracy и confusion_matrix на тестовой выборке.

Обратите внимание, что это задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные и тюнить параметры логистической регрессии.

In [226]:
df3 = df.drop(['price', 'odometer/price_std'], axis = 1)

x = df3.drop(['price_category'], axis=1)
y = df3['price_category']
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)

logreg = LogisticRegression()

logreg.fit(x_train, y_train)
pred_train = logreg.predict(x_train)
logreg_pred = logreg.predict(x_test)

print (f'accuracy_score на тренировочной выборке = {accuracy_score(y_train, pred_train)}')
print (f'accuracy_score на тестовой выборке = {accuracy_score(y_test, logreg_pred)}')
print (confusion_matrix(y_test, logreg_pred))

accuracy_score на тренировочной выборке = 0.3392247140947572
accuracy_score на тестовой выборке = 0.32432432432432434
[[  0   0 997]
 [  0   0 953]
 [  0   0 936]]


In [240]:
df3 = df.drop(['price', 'odometer/price_std', 'id'], axis = 1)

x = df3.drop(['price_category'], axis=1)
y = df3['price_category']
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=33)

logreg = LogisticRegression(C = 10, max_iter=100, penalty='l1', solver='liblinear')

logreg.fit(x_train, y_train)
pred_train = logreg.predict(x_train)
logreg_pred = logreg.predict(x_test)

print (f'accuracy_score на тренировочной выборке = {accuracy_score(y_train, pred_train)}')
print (f'accuracy_score на тестовой выборке = {accuracy_score(y_test, logreg_pred)}')
print (confusion_matrix(y_test, logreg_pred))

accuracy_score на тренировочной выборке = 0.8780260707635009
accuracy_score на тестовой выборке = 0.7559055118110236
[[891  26 132]
 [ 31 901 162]
 [183 241 608]]


### **Задача 3. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. С помощью данного алгоритма добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии. 

Увеличение точности в данном задании, по сравнению с предыдущим, должно быть больше увеличения 0.01 по метрике accuracy.

In [244]:
mlp = MLPClassifier (random_state=42, max_iter=500, hidden_layer_sizes = (100, 20), activation = 'tanh')
mlp.fit(x_train, y_train)
pred_train =  mlp.predict (x_train)
pred_test = mlp.predict(x_test)
print (f'accuracy_score на тренировочной выборке = {accuracy_score(y_train, pred_train)}')
print (f'accuracy_score на тестовой выборке = {accuracy_score(y_test, pred_test)}')

accuracy_score на тренировочной выборке = 1.0
accuracy_score на тестовой выборке = 0.7826771653543307


**Задача 4. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, обоснуйте свой выбор.

In [248]:
rf_clf = RandomForestClassifier()
rf_clf.fit(x_train, y_train)
pred_train_rf = rf_clf.predict(x_train)
pred_test_rf = rf_clf.predict(x_test)
print (f'accuracy_score на тренировочной выборке = {accuracy_score(y_train, pred_train_rf)}')
print (f'accuracy_score на тестовой выборке = {accuracy_score(y_test, pred_test_rf)}')

accuracy_score на тренировочной выборке = 1.0
accuracy_score на тестовой выборке = 0.7581102362204725


In [252]:
# Сравнение качества 3 моделей
acc_list_logreg, acc_list_mlp, acc_list_rf_clf = [], [], []

for i in range (10):  
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)

    logreg.fit(x_train, y_train)
    mlp.fit(x_train, y_train)
    rf_clf.fit (x_train, y_train)

    pred_test_logreg = logreg.predict(x_test)
    pred_test_mlp = mlp.predict(x_test)
    pred_test_rf_clf = rf_clf.predict(x_test)

    acc_list_logreg.append(accuracy_score(y_test, pred_test_logreg))
    acc_list_mlp.append(accuracy_score(y_test, pred_test_mlp))
    acc_list_rf_clf.append(accuracy_score(y_test, pred_test_rf_clf))

print (acc_list_logreg)
print (acc_list_mlp)
print (acc_list_rf_clf)

[0.7605682605682605, 0.764033264033264, 0.7442827442827443, 0.7636867636867637, 0.7584892584892585, 0.7612612612612613, 0.7494802494802495, 0.7494802494802495, 0.7515592515592515, 0.7713097713097713]
[0.7643797643797644, 0.7848232848232848, 0.7664587664587664, 0.7674982674982676, 0.7744282744282744, 0.7671517671517671, 0.7758142758142759, 0.7647262647262647, 0.7778932778932779, 0.77997227997228]
[0.7588357588357588, 0.770963270963271, 0.7394317394317395, 0.7605682605682605, 0.7605682605682605, 0.7522522522522522, 0.7702702702702703, 0.7616077616077616, 0.7671517671517671, 0.7674982674982676]


In [256]:
import numpy as np
print (f'средняя результативность 10 прогонов logreg = {np.mean (acc_list_logreg)}')
print (f'средняя результативность 10 прогонов mlp = {np.mean(acc_list_mlp)}')
print (f'средняя результативность 10 прогонов rf_clf = {np.mean(acc_list_rf_clf)}')

# С данными настройками наиболее результативной оказалась нейросеть. Наименее - логистическая регрессия. 
# Однако, нейросеть - наиболее требовательна к ресурсам и обучается дольше других моделей.
# В этом, видимо, и заключается выбор: ресурсы или точность.

средняя результативность 10 прогонов logreg = 0.7574151074151074
средняя результативность 10 прогонов mlp = 0.7723146223146223
средняя результативность 10 прогонов rf_clf = 0.7609147609147608


**Задача 5. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвёртую колонку `target` положите тот класс, который предсказало большинство классификаторов; например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`;

     если в строке три разных класса (`high, medium, low`), придумайте свою стратегию по выбору значения; самая простая стратегия — выбрать рандомно одно значение из трёх;

- посчитайте точность предсказания с помощью голосования; выведите значения метрик accuracy и confusion_matrix.

Добейтесь значения точности > 78%.

In [266]:
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=[('logreg', logreg), ('mlp', mlp), ('rf_clf', rf_clf)], voting='soft')
vc.fit(x_train, y_train)

VotingClassifier(estimators=[('logreg',
                              LogisticRegression(C=10, penalty='l1',
                                                 solver='liblinear')),
                             ('mlp',
                              MLPClassifier(activation='tanh',
                                            hidden_layer_sizes=(100, 20),
                                            max_iter=500, random_state=42)),
                             ('rf_clf', RandomForestClassifier())],
                 voting='soft')

In [267]:
d = {'logreg': pred_test_logreg, 'mlp': pred_test_mlp, 'rf_clf':pred_test_rf_clf}
pred_df = pd.DataFrame(data=d)
pred_df['target'] = vc.predict(x_test)
pred_df.head(1)

logreg     mlp  rf_clf  target
0  medium  medium  medium  medium

In [277]:
accuracy_score(y_test, vc.predict(x_test))

0.7976437976437977

In [276]:
pred_df[(pred_df.logreg != pred_df.mlp) & (pred_df.logreg != pred_df.rf_clf) & (pred_df.mlp != pred_df.rf_clf)]
# параметр voting='soft' в VotingClassifier для моделей, поддерживающих predict_prob, дает возможность 
# в случае 3 различных ответов, выбирать ответ с наибольшей вероятностью.
# Ниже - выборка как раз таких случаев и результат взвешивания их вероятностей в target

logreg     mlp  rf_clf  target
91      high     low  medium    high
144     high  medium     low     low
186   medium    high     low  medium
215      low  medium    high  medium
218   medium    high     low    high
265      low    high  medium     low
440   medium    high     low    high
655     high  medium     low  medium
685     high  medium     low  medium
713   medium    high     low    high
716   medium     low    high     low
720      low  medium    high  medium
1014     low    high  medium  medium
1123    high  medium     low  medium
1325    high  medium     low    high
1388  medium     low    high     low
1578     low  medium    high  medium
1638     low    high  medium     low
1817    high     low  medium    high
2089     low    high  medium    high
2289     low  medium    high     low
2316  medium     low    high     low
2318     low  medium    high  medium
2338    high  medium     low  medium
2428    high  medium     low  medium
2431  medium     low    high     low
2498     low  medium    high  medium
2528  medium     low    high     low
2688    high     low  medium     low
2716    high  medium     low  medium
2736    high     low  medium  medium
2802     low  medium    high  medium
2830  medium    high     low  medium
2859  medium     low    high     low

**Примечание**

В этой практической работе перед вами встал выбор: включать ли колонку `id`. При удалении данной колонки во время обучения логистической регрессии качество заметно улучшается.

Обучать любую модель (будь то логистическая, линейная регрессия или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь подогнать результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе частных случаев и, возможно, не обратит внимание на общие зависимости.   